name: Deploy To-Do App to Azure VM

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:${{ github.sha }} ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:${{ github.sha }}

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${{ github.sha }} ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${{ github.sha }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_PUBLIC_IP }}
          username: ${{ secrets.VM_SSH_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:${{ github.sha }}
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${{ github.sha }}
            docker-compose down
            cat > docker-compose.yml <<EOF
version: '3.8'
services:
  backend:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/todo-backend:${{ github.sha }}
    ports: ["3000:3000"]
    networks: [app-net]
  frontend:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/todo-frontend:${{ github.sha }}
    ports: ["80:80"]
    depends_on: [backend]
    networks: [app-net]
networks:
  app-net:
    driver: bridge
EOF
            docker-compose up -d